[package]
authors = ["Ockam Developers"]
categories = ["cryptography", "asynchronous", "authentication","embedded", "network-programming"]
description = "Ockam Node implementation crate"
edition = "2018"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node"
keywords = ["ockam", "crypto", "cryptography", "network-programming", "encryption"]
license = "Apache-2.0"
name = "ockam_node"
version = "0.12.0-dev"

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.14.0-dev"     }
tokio = {version = "1.6.0", features = ["full"]}
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "env-filter"] }
