[package]
authors = ["Ockam Developers"]
categories = ["cryptography", "authentication", "algorithms", "network-programming", "asynchronous"]
description = "Ockam Node implementation crate"
edition = "2018"
keywords = ["ockam"]
license = "Apache-2.0"
name = "ockam_node"
version = "0.3.0"

[dependencies]
ockam_core = {path = "../ockam_core", version = "0.5.0"}
tokio = {version = "1.3.0", features = ["full"]}
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "env-filter"] }
