[package]
authors = ["Ockam Developers"]
categories = ["cryptography", "asynchronous", "authentication","embedded", "network-programming"]
description = "Ockam Node implementation crate"
edition = "2018"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node"
keywords = ["ockam", "crypto", "cryptography", "network-programming", "encryption"]
license = "Apache-2.0"
name = "ockam_node"
version = "0.25.0-dev"

[features]
default = ["std"]

# Option (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_core/std", "tokio", "tracing-subscriber"]

# Option: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["ockam_core/no_std", "ockam_node_no_std/no_std", "heapless"]

# Option: "alloc" enables support for heap allocation on "no_std"
# platforms, requires nightly.
alloc = ["ockam_core/alloc", "ockam_node_no_std/alloc"]

# Option: "dump_internals" when set, will dump the internal state of workers at startup via the trace! macro.
dump_internals = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.27.0-dev"  , default_features = false }
tokio = {version = "1.10", features = ["full"], optional = true}
tracing = { version = "0.1", default_features = false }
tracing-subscriber = { version = "0.2", features = ["fmt", "env-filter"], optional = true }
heapless = { version = "0.7", features = [ "mpmc_large" ], optional = true }
ockam_node_no_std = { path = "../ockam_node_no_std", version = "0.2.0-dev" , default-features = false, optional = true }

[dev-dependencies]
async-trait =  { version = "0.1" }
