[package]
authors = ["Ockam Developers"]
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "embedded",
    "network-programming",
]
description = "Ockam Node implementation crate"
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_node"
keywords = [
    "ockam",
    "crypto",
    "cryptography",
    "network-programming",
    "encryption",
]
license = "Apache-2.0"
name = "ockam_node"
version = "0.79.0"
publish = true
rust-version = "1.56.0"

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_core/std", "tokio", "tracing-subscriber", "tracing-error", "alloc", "futures/std", "minicbor/std"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["ockam_core/no_std", "heapless"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["ockam_core/alloc", "ockam_executor/alloc", "futures/alloc", "minicbor/alloc"]

# Feature: "dump_internals" when set, will dump the internal state of
# workers at startup via the trace! macro.
dump_internals = []
# TODO should these features be combined?
metrics = []

# Feature: "debugger" enables functionality to trace addresses and
# message flows within Ockam apps.
debugger = ["ockam_core/debugger"]

tag = ["cddl-cat", "once_cell", "ockam_core/tag"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.76.0", default_features = false }
ockam_macros = { path = "../ockam_macros", version = "^0.27.0" }
tokio = { version = "1.25", default-features = false, optional = true, features = [
    "sync",
    "time",
    "rt",
    "rt-multi-thread",
    "macros",
] }
futures = { version = "0.3.26", default-features = false }
tracing = { version = "0.1", default_features = false }
tracing-error = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
], optional = true }
heapless = { version = "0.7", features = ["mpmc_large"], optional = true }
ockam_executor = { path = "../ockam_executor", version = "^0.44.0", default-features = false, optional = true }
serde_bare = { version = "0.5.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
minicbor = { version = "0.19.0", features = ["derive"] }
once_cell = { version = "1", optional = true, default-features = false }
cddl-cat = { version = "0.6.1", optional = true }
