[package]
authors = ["Ockam Developers"]
description = "Ockam Node implementation crate"
edition = "2018"
license = "Apache-2.0"
name = "ockam_node"
version = "0.1.1"

[dependencies]
async-trait = "0.1.42"
hashbrown = "0.9.1"
ockam_core = {path = "../ockam_core", version = "0.2.0"}
tokio = {version = "1.1.0", features = ["full"]}
