[package]
authors = ["Ockam Developers"]
categories = ["cryptography", "authentication", "algorithms", "network-programming", "asynchronous"]
description = "Ockam Node implementation crate"
edition = "2018"
keywords = ["ockam"]
license = "Apache-2.0"
name = "ockam_node"
version = "0.2.0"

[dependencies]
async-trait = "0.1.42"
hashbrown = "0.9.1"
ockam_core = {path = "../ockam_core", version = "0.3.0"}
tokio = {version = "1.1.0", features = ["full"]}
futures = "0.3"
