[package]
name = "ockam_node"
version = "0.109.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "embedded",
  "network-programming",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = [
  "ockam",
  "crypto",
  "cryptography",
  "network-programming",
  "encryption",
]
license = "Apache-2.0"
publish = true
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_node"
rust-version = "1.56.0"
description = """This crate provides an implementation of an Ockam [Ockam][main-ockam-crate-link]
Node and is intended for use by crates that provide features and add-ons
to the main [Ockam][main-ockam-crate-link] library.

The main [Ockam][main-ockam-crate-link] crate re-exports types defined in
this crate, when the `"std"` feature is enabled.
"""

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = [
  "chrono",
  "ockam_core/std",
  "ockam_transport_core/std",
  "once_cell/std",
  "opentelemetry",
  "tokio",
  "tracing-opentelemetry",
  "tracing-subscriber",
  "tracing-error",
  "alloc",
  "futures/std",
  "minicbor/std",
  "storage",
  "fs2",
]

# Feature: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["ockam_core/no_std", "ockam_transport_core/no_std", "heapless"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["ockam_core/alloc", "ockam_executor/alloc", "futures/alloc", "minicbor/alloc"]

# Feature: "dump_internals" when set, will dump the internal state of
# workers at startup via the trace! macro.
dump_internals = []
# TODO should these features be combined?
metrics = []

# Feature: "debugger" enables functionality to trace addresses and
# message flows within Ockam apps.
debugger = ["ockam_core/debugger"]

storage = ["std", "time", "serde_json", "sqlx", "tokio-retry", "regex"]

[dependencies]
cfg-if = "1.0.0"
chrono = { version = "0.4", optional = true }
fs2 = { version = "0.4.3", optional = true }
futures = { version = "0.3.30", default-features = false }
heapless = { version = "0.8", features = ["mpmc_large"], optional = true }
minicbor = { version = "0.20.0", features = ["derive"] }
ockam_core = { path = "../ockam_core", version = "^0.102.0", default_features = false }
ockam_executor = { path = "../ockam_executor", version = "^0.71.0", default-features = false, optional = true }
ockam_macros = { path = "../ockam_macros", version = "^0.34.0" }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.75.0", default-features = false, optional = true }
once_cell = { version = "1.19.0", optional = true, default-features = false }
opentelemetry = { version = "0.21.0", features = ["logs", "metrics", "trace"], optional = true }
regex = { version = "1.10.3", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_bare = { version = "0.5.0", default-features = false }
serde_json = { version = "1", optional = true }
sqlx = { version = "0.7.3", optional = true, features = ["sqlite", "migrate", "runtime-tokio"] }
time = { version = "0.3.34", default-features = false, optional = true }
tokio = { version = "1.36", default-features = false, optional = true, features = ["sync", "time", "rt", "rt-multi-thread", "macros"] }
tokio-retry = { version = "0.3.0", optional = true }
tracing = { version = "0.1", default_features = false }
tracing-error = { version = "0.2", optional = true }
tracing-opentelemetry = { version = "0.22.0", optional = true }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"], optional = true }

[dev-dependencies]
hex = { version = "0.4", default-features = false }
tempfile = { version = "3.10.0" }
