[package]
name = "ockam_transport_websocket"
version = "0.83.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "network-programming",
  "embedded",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "network", "networking", "websocket"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_transport_websocket"
rust-version = "1.56.0"
description = """
WebSocket Transport for the Ockam Routing Protocol.
"""

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = [
  "ockam_core/std",
  "ockam_node/std",
  "ockam_transport_core/std",
  "tokio",
  "tokio-tungstenite",
  "alloc",
]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`).
alloc = [
  "ockam_core/alloc",
  "ockam_node/alloc",
  "ockam_transport_core/alloc",
  "serde/alloc",
]

[dependencies]
futures-util = { version = "0.3", default-features = false, features = ["tokio-io"] }
ockam_core = { path = "../ockam_core", version = "^0.89.0", default_features = false }
ockam_node = { path = "../ockam_node", version = "^0.94.0", default_features = false }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.62.0", default_features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tokio = { version = "1.33", default-features = false, optional = true, features = ["rt-multi-thread", "sync", "net", "macros", "time", "io-std"] }
tokio-tungstenite = { version = "0.20.1", default-features = false, optional = true, features = ["connect"] }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
ockam_macros = { path = "../ockam_macros", version = "^0.32.0" }
