[package]
authors = ["Ockam Developers"]
name = "okta-plugin"
version = "0.1.0"
edition = "2018"

[lib]
name = "oktaplugin"

[dependencies]
base64-url = "1.4"
colored = "2.0"
dirs = "3.0"
generic-array = "0.12"
isahc = "0.9"
ockam = { version = "*", path = "../../../ockam" }
rpassword = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bare = { git = "ssh://git@github.com/ockam-network/serde_bare.git", branch = "ockam-network/no_std+alloc" }
serde-big-array = "0.3"
structopt = "0.3"
