[package]
name = "ockam_abac"
version = "0.24.0"
authors = ["Ockam Developers"]
categories = ["cryptography", "authorization"]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "encryption", "authorization"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_abac"
description = "Attribute based authorization control"

[features]
default = ["std"]
no_std = ["ockam_core/no_std", "ockam_identity/no_std"]
alloc = ["ockam_core/alloc", "ockam_identity/alloc"]
repl = ["rustyline", "rustyline-derive", "std"]
std = [
  "ockam_core/std",
  "ockam_identity/std",
  "minicbor/std",
  "tracing/std",
  "either/use_std",
  "lmdb",
  "once_cell/std",
  "regex",
  "tokio",
  "wast",
]
lmdb = ["tokio", "lmdb-rkv"]
sqlite = ["rusqlite"]

[dependencies]
either = { version = "1.9.0", default-features = false }
lmdb-rkv = { version = "0.14.0", optional = true }
minicbor = { version = "0.19.0", features = ["derive", "alloc"] }
ockam_core = { version = "0.83.0", path = "../ockam_core", default-features = false }
ockam_executor = { version = "0.51.0", path = "../ockam_executor", default-features = false }
ockam_identity = { version = "0.78.0", path = "../ockam_identity", default-features = false }
once_cell = { version = "1.18.0", default-features = false, features = ["alloc"] }
# optional:
regex = { version = "1.9.3", default-features = false, optional = true }
rusqlite = { version = "0.29.0", optional = true }
rustyline = { version = "12.0.0", optional = true }
rustyline-derive = { version = "0.9.0", optional = true }
str-buf = "3.0.1"
tokio = { version = "1.31", default-features = false, optional = true, features = ["sync", "time", "rt", "rt-multi-thread", "macros"] }
tracing = { version = "0.1", default-features = false }
wast = { version = "62.0.1", default-features = false, optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
rand = "0.8.5"
tempfile = "3.7.1"

[[bin]]
name = "repl"
test = true
required-features = ["repl"]
path = "src/bin/repl.rs"
