[package]
name = "ockam_abac"
version = "0.43.0"
authors = ["Ockam Developers"]
categories = ["cryptography", "authorization"]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "encryption", "authorization"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_abac"
description = "Attribute based authorization control"

[features]
default = ["std"]
no_std = ["ockam_core/no_std", "ockam_identity/no_std", "ockam_executor"]
alloc = ["ockam_core/alloc", "ockam_identity/alloc"]
repl = ["rustyline", "rustyline-derive", "std"]
std = [
  "ockam_core/std",
  "ockam_identity/std",
  "ockam_node/std",
  "minicbor/std",
  "tracing/std",
  "either/use_std",
  "once_cell/std",
  "sqlx",
  "regex",
  "tokio",
  "wast",
]

[dependencies]
either = { version = "1.9.0", default-features = false }
minicbor = { version = "0.20.0", features = ["derive", "alloc"] }
ockam_core = { version = "0.97.0", path = "../ockam_core", default-features = false }
ockam_identity = { version = "0.97.0", path = "../ockam_identity", default-features = false }
ockam_node = { version = "0.102.0", path = "../ockam_node", default-features = false }
once_cell = { version = "1.19.0", default-features = false, features = ["alloc"] }

# optional:
ockam_executor = { version = "0.65.0", path = "../ockam_executor", default-features = false, optional = true }
regex = { version = "1.10.2", default-features = false, optional = true }
rusqlite = { version = "0.30.0", optional = true }
rustyline = { version = "13.0.0", optional = true }
rustyline-derive = { version = "0.10.0", optional = true }
sqlx = { version = "0.7.3", optional = true }
str-buf = "3.0.1"
tokio = { version = "1.35", default-features = false, optional = true, features = ["sync", "time", "rt", "rt-multi-thread", "macros"] }
tracing = { version = "0.1", default-features = false }
wast = { version = "69.0.1", default-features = false, optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
rand = "0.8.5"
tempfile = "3.8.0"

[[bin]]
name = "repl"
test = true
required-features = ["repl"]
path = "src/bin/repl.rs"
