[package]
name        = "ockam_abac"
version     = "0.14.0"
authors     = ["Ockam Developers"]
edition     = "2021"
license     = "Apache-2.0"
homepage    = "https://github.com/build-trust/ockam"
repository  = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_abac"
readme      = "README.md"
categories  = ["cryptography", "authorization"]
keywords    = ["ockam", "crypto", "encryption", "authorization"]
description = "Attribute based authorization control"
publish     = true

[features]
default = ["std"]
no_std  = ["ockam_core/no_std", "ockam_identity/no_std"]
alloc   = ["ockam_core/alloc", "ockam_identity/alloc"]
repl    = ["rustyline", "rustyline-derive", "std"]
std     = [
  "ockam_core/std",
  "ockam_identity/std",
  "minicbor/std",
  "tracing/std",
  "either/use_std",
  "once_cell/std"
]

[dependencies]
either           = { version = "1.8.1", default-features = false }
minicbor         = { version = "0.19.0", features = ["derive", "alloc"] }
ockam_core       = { version = "0.74.0", path = "../ockam_core", default-features = false }
ockam_identity   = { version = "0.68.0", path = "../ockam_identity", default-features = false }
once_cell        = { version = "1.17.1", default-features = false, features = ["alloc"] }
regex            = "1.7.1"
str-buf          = "3.0.1"
wast             = { version = "54.0.0", default-features = false }
tracing          = { version = "0.1.34", default-features = false }
# optional:
rustyline        = { version = "10.1.1", optional = true }
rustyline-derive = { version = "0.8.0", optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
rand       = "0.8.5"

[[bin]]
name = "repl"
test = true
required-features = ["repl"]
