[package]
name = "ockam-ffi"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_ffi"
readme = "README.md"
categories = ["cryptography"]
keywords = ["ockam", "ffi", "cryptography", "crypto", "curve25519", "xeddsa", "aes", "gcm", "encryption", "aead", "iot"]
description = """FFI layer for ockam_vault.
"""

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[profile.release]
lto = true

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.4.0" }
ockam_vault_core = {path = "../ockam_vault_core", version = "0.2.1" }
ockam_vault = { path = "../ockam_vault", version = "0.2.1" }
lazy_static = { version = "1.4" }
