[package]
name = "ockam-ffi"
version = "0.22.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_ffi"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","external-ffi-bindings", "api-bindings"]
keywords = ["ockam", "crypto", "ffi", "cryptography", "bindings"]
description = """FFI layer for ockam_vault.
"""

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
bls = ["ockam_vault/bls"]

[profile.release]
lto = true

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.32.0"     }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.26.0"     }
ockam_vault = { path = "../ockam_vault", version = "0.26.0"     }
lazy_static = "1.4"
