[package]
name = "ockam-ffi"
version = "0.71.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "external-ffi-bindings",
  "api-bindings",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "ffi", "cryptography", "bindings"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_ffi"
rust-version = "1.56.0"
description = """FFI layer for ockam_vault.
"""

[lib]
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
futures = { version = "0.3.28" }
lazy_static = "1.4"
ockam_core = { path = "../ockam_core", version = "^0.79.0" }
ockam_vault = { path = "../ockam_vault", version = "^0.75.0" }
tokio = { version = "1.28", features = ["full"] }
