[package]
name = "ockam-ffi"
version = "0.68.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/build-trust/ockam"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_ffi"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "external-ffi-bindings",
    "api-bindings",
]
keywords = ["ockam", "crypto", "ffi", "cryptography", "bindings"]
description = """FFI layer for ockam_vault.
"""
publish = true
rust-version = "1.56.0"

[lib]
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.76.0" }
ockam_vault = { path = "../ockam_vault", version = "^0.72.0" }
lazy_static = "1.4"
tokio = { version = "1.25", features = ["full"] }
futures = { version = "0.3.26" }
