[package]
name = "ockam_get_started"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[dependencies]
ockam = {path = "../../../implementations/rust/ockam/ockam", features = ["ockam_transport_tcp", "ockam_vault"]}

[dev-dependencies]
rand = { version = "*", features = ["std_rng"] }

