[package]
name = "ockam-tcp-manager"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ockam-no-std-traits = { version = "0.1", path = "../no_std_traits" }
ockam-message = { version = "0.1", path = "../message" }
libc = "0.2.80"
libc-print = "0.1.14"