[package]
name = "example_runner"
license = "Apache-2.0"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "*"
ron = "*"
serde = "*"
anyhow = "*"
rand = "*"
