[package]
name = "credentials"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
description = """
An example of issuing, holding, and verifying a credential
"""

[dependencies]
ockam = { version = "0.2", path = "../../ockam/ockam"}


[[bin]]
name = "issuer"
path = "src/issuer.rs"

[[bin]]
name = "holder"
path = "src/holder.rs"

[[bin]]
name = "verifier"
path = "src/verifier.rs"
