[package]
name = "credentials"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
description = """
An example of issuing, holding, and verifying a credential
"""

[dependencies]
ockam = { version = "0.2", path = "../../ockam/ockam"}
serde = { version = "1.0", features = ["derive"] }
serde_bare = "0.3"
serde-big-array = "0.3"

[[bin]]
name = "issuer"
path = "src/issuer.rs"

[[bin]]
name = "holder"
path = "src/holder.rs"

[[bin]]
name = "verifier"
path = "src/verifier.rs"
