[package]
authors = ["Ockam Developers"]
description = """Example projects using the Ockam APIs"""
version = "0.14.0-dev"
edition = "2018"
homepage = "https://github.com/ockam-network/ockam"
keywords = ["ockam", "crypto", "cryptography"]
license = "Apache-2.0"
name = "ockam_examples"
readme = "README.md"
repository = "https://github.com/ockam-network/ockam"

[dependencies]
ockam = { path = "../ockam", features = ["ockam_vault", "ockam_transport_tcp"]}
tracing = "0.1.26"
