[package]
name = "ockam_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"

[dependencies]
ockam = { path = "../ockam", version = "0" }
ockam_node = { path = "../ockam_node", version = "0" }
async-trait = "0"
chrono = { version = "0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_bare = "0"
serde-big-array = "0"

