[package]
authors = ["Ockam Developers"]
description = """Example projects using the Ockam APIs"""
version = "0.1.0"
edition = "2018"
homepage = "https://github.com/ockam-network/ockam"
keywords = ["ockam", "crypto", "cryptography"]
license = "Apache-2.0"
name = "ockam_examples"
readme = "README.md"
repository = "https://github.com/ockam-network/ockam"

[dependencies]
ockam = { path = "../ockam", version = "*"}
ockam_transport_tcp = { path = "../ockam_transport_tcp", version = "*"}

# [workspace]
# members = ["example_projects/*"]
# default-members = ["example_projects/*"]
