
version: 2
updates:

  # Maintain dependencies for elixir ockam application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for elixir ockam_hub application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_hub"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for elixir ockam_node_web application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_node_web"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for elixir ockam_vault_software application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_vault_software"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_core crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_core"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_ffi crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_ffi"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_node crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_node"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_node_attribute crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_node_attribute"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_node_no_std crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_node_no_std"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_node_tcp crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_node_tcp"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_vault crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_vault"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for rust ockam_vault_core crate
  - package-ecosystem: "cargo"
    directory: "/implementations/rust/ockam_vault_core"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
