[package]
name = "worker_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
ockam = { path = "../../../ockam" }
ockam_node = { path = "../../../ockam_node" }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tokio = { version = "1.0", features = ["full"] }
