[package]
name = "ockam_executor"
version = "0.65.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "no-std",
  "algorithms",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "encryption", "authentication"]
license = "Apache-2.0"
publish = true
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_executor"
rust-version = "1.56.0"
description = "Ockam async executor crate"

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["alloc", "futures/std", "ockam_core/std"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["futures/alloc", "ockam_core/alloc"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library, requires nightly.
no_std = ["ockam_core/no_std"]

[dependencies]
crossbeam-queue = { version = "0.3.9", default_features = false, features = ["alloc"] }
futures = { version = "0.3.29", default-features = false, features = ["async-await"] }
heapless = { version = "0.8", features = ["mpmc_large"] }
ockam_core = { path = "../ockam_core", version = "^0.97.0", default_features = false }
pin-project-lite = "0.2"
pin-utils = "0.1.0"
tracing = { version = "0.1", default_features = false }
