[package]
name = "management_app"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"


[dependencies]
lazy_static = "1.4"
ockam = { path = "../../../ockam/ockam" }
ockam_vault = {  path = "../../../ockam/ockam_vault" }
okta-plugin = { path = "../" }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_bare = { git = "https://github.com/ockam-network/serde_bare.git", rev = "fdbb431", default-features = false }
serde_json = "1.0"
structopt = "0.3"
