[package]
name = "management_app"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"


[dependencies]
lazy_static = "1.4"
ockam = { version = "0.3", path = "../../../ockam/ockam" }
ockam_vault = { version = "0.3", path = "../../../ockam/ockam_vault" }
okta-plugin = { version = "0.1", path = "../" }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_bare = "0.3"
serde_json = "1.0"
structopt = "0.3"
