[package]
name = "ockam_credential"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_credential"
readme = "README.md"
keywords = ["ockam", "authorization", "anonymous", "zero-knowledge", "credential"]
categories = ["cryptography", "no-std"]
description = """
Attribute based, privacy preserving, anonymous credentials.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[features]
default = ["std"]
std = ["ockam_core/std", "alloc", "bbs", "ff", "pairing-plus"]
alloc = ["serde/alloc"]
no_std = ["heapless"]

[dependencies]
bbs = { version = "0.4", optional = true }
digest = { version = "0.8", optional = true }
ff = { version = "0.6", package = "ff-zeroize", optional = true }
heapless = { version = "0.6", optional = true }
ockam_core = { version = "0.2.0", default-features = false, path = "../ockam_core" }
pairing-plus = { version = "0.19", optional = true }
rand_core = { version = "0.6", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
