[package]
authors = ["Ockam Developers"]
name = "okta-plugin"
version = "0.1.0"
edition = "2018"

[lib]
name = "oktaplugin"

[profile.release]
lto = true

[dependencies]
base64-url = "1.4"
colored = "2.0"
dirs = "3.0"
generic-array = "0.12"
isahc = "0.9"
ockam = { version = "0.3", path = "../../ockam/ockam" }
rpassword = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bare = "0.3"
serde-big-array = "0.3"
structopt = "0.3"
