version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    networks:
      - acme_corp

  ockam:
    depends_on:
      - app
    image: ghcr.io/build-trust/ockam
    container_name: ockam-outlet
    environment:
      ENROLLMENT_TICKET: ${ENROLLMENT_TICKET}
      OCKAM_DEVELOPER: ${OCKAM_DEVELOPER:-false}
      OCKAM_OPENTELEMETRY_EXPORT: "false"
    command:
      - node
      - create
      - --foreground
      - --configuration
      - |
        name: api_outlet_node
        ticket: ${ENROLLMENT_TICKET}

        relay: acme_api

        tcp-outlet:
          to: app:15000
          allow: acme_api_client
    networks:
      - acme_corp

networks:
  acme_corp:
    driver: bridge
