[package]
name = "okta_example_management_service"
version = "0.1.0"
authors = ["Michael Lodder <mike@ockam.io>"]
edition = "2018"
publish = false

[dependencies]
arrayref = "0.3"
base64-url = "1.4"
owo-colors = "3"
isahc = "0.9"
lazy_static = "1.4"
percent-encoding = "2.1"
rand = "0.7"
ockam = { path = "../../../../ockam" }
ockam_vault = { path = "../../../../ockam_vault" }
ockam_vault_sync_core = { path = "../../../../ockam_vault_sync_core" }
ockam_key_exchange_core = { path = "../../../../ockam_key_exchange_core" }
ockam_key_exchange_x3dh = { path = "../../../../ockam_key_exchange_x3dh" }
okta-plugin = { version = "0.1", path = "../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
