[package]
name = "management_service"
version = "0.1.0"
authors = ["Michael Lodder <mike@ockam.io>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
arrayref = "0.3"
base64-url = "1.4"
colored = "2.0"
isahc = "0.9"
lazy_static = "1.4"
percent-encoding = "2.1"
rand = "0.7"
ockam = { path = "../../../ockam/ockam" }
ockam_vault = { path = "../../../ockam/ockam_vault" }
ockam_key_exchange_core = { path = "../../../ockam/ockam_key_exchange_core" }
ockam_key_exchange_x3dh = { path = "../../../ockam/ockam_key_exchange_x3dh" }
okta-plugin = { version = "0.1", path = "../" }
serde = { version = "1.0", features = ["derive"] }
serde_bare = { git = "ssh://git@github.com/ockam-network/serde_bare.git", branch = "ockam-network/no_std+alloc" }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
