[package]
name = "ockam_key_exchange_x3dh"
version = "0.16.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_x3dh"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","embedded", "no-std"]
keywords = ["ockam", "crypto", "x3dh", "cryptography", "encryption"]
description = """The Ockam X3DH impementation.
"""

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.25.0-dev"                           }
ockam_vault_core = { path = "../ockam_vault_core" , version = "0.19.0-dev"                           }
ockam_key_exchange_core = { path = "../ockam_key_exchange_core" , version = "0.17.0-dev"                           }
arrayref = "0.3"
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
ockam_vault_sync_core = { path = "../ockam_vault_sync_core", version = "0.16.0-dev"                          }
ockam_vault = { path = "../ockam_vault", version = "0.19.0-dev"                          }
