[package]
name = "ockam_key_exchange_x3dh"
version = "0.1.1"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_x3dh"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","embedded", "no-std"]
keywords = ["ockam", "crypto", "x3dh", "cryptography", "encryption", "iot"]
description = """The Ockam X3DH impementation.
"""

[dependencies]
ockam_core = { version = "0", path = "../ockam_core" }
ockam_vault_core = { version = "0", path = "../ockam_vault_core" }
ockam_key_exchange_core = { version = "0", path = "../ockam_key_exchange_core" }
arrayref = "0.3"
subtle = "2.3"
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
ockam_vault = { version = "0", path = "../ockam_vault" }
