[package]
name = "ockam-vault-sys"
version = "0.9.0"
authors = ["Ockam Developers"]
edition = "2018"

links = "ockam_vault"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.53"
which = "3.1"
walkdir = "2.3.1"
cmake = "0.1"
