[package]
name = "ockam_vault_aws"
version = "0.20.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "no-std",
  "algorithms",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "cryptography", "authentication", "no-std"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_vault_aws"
rust-version = "1.56.0"
description = """An AWS KMS Ockam Vault implementation.
"""

[lib]
crate-type = ["rlib"]
path = "src/lib.rs"

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = [
  "ockam_core/std",
  "ockam_macros/std",
  "ockam_node/std",
  "ockam_vault/std",
]

storage = ["ockam_vault/storage"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library, requires nightly.
no_std = [
  "ockam_core/no_std",
  "ockam_macros/no_std",
  "ockam_node/no_std",
  "ockam_vault/no_std",
]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["ockam_core/alloc", "ockam_node/alloc", "ockam_vault/alloc"]

# Feature: "credentials-sso" enables support for sso on aws-config
credentials-sso = ["aws-config/sso"]

[dependencies]
aws-config = { version = "1.0.3", default-features = false, features = ["rustls", "rt-tokio"] }
aws-sdk-kms = { version = "1.4.0", default-features = false, features = ["rustls"] }
ockam_core = { path = "../ockam_core", version = "^0.97.0", default_features = false }
ockam_macros = { path = "../ockam_macros", version = "^0.32.0", default-features = false }
ockam_node = { path = "../ockam_node", version = "^0.102.0", default_features = false }
ockam_vault = { path = "../ockam_vault", version = "^0.95.0", default_features = false }
p256 = { version = "0.13.2", default_features = false }
sha2 = { version = "0.10", default-features = false }
thiserror = { version = "1.0.50" }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
aws-credential-types = { version = "1.0.3", default-features = false, features = ["test-util"] }
hex = { version = "0.4", default-features = false }
tokio = { version = "1.35", features = ["full"] }
