[package]
name = "signature_bbs_plus"
version = "0.36.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/signature_bbs_plus"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "no-std",
    "algorithms",
]
keywords = ["ockam", "crypto", "signature", "signing", "bls"]
description = """The Ockam BBS+ signature impementation.
"""
publish = true
rust-version = "1.56.0"

[dependencies]
bls12_381_plus = { version = "0.5", default-features = false }
blake2 = { version = "0.9", default-features = false }
digest = { version = "0.9", default-features = false }
ff = { version = "0.10", default-features = false }
group = "0.10"
hmac-drbg = "0.3"
managed = { version = "0.8", default-features = false, features = ["map"] }
pairing = "0.20"
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"] }
signature_core = { version = "^0.35.0", path = "../signature_core" }
signature_bls = { version = "^0.33.0", path = "../signature_bls" }
subtle = { version = "2.4", default-features = false }
typenum = "1.13"
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.3"
rand = "0.8.3"
