[package]
name = "signature_bbs_plus"
version = "0.17.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/signature_bbs_plus"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std","algorithms"]
keywords = ["ockam", "crypto", "signature", "signing", "bls"]
description = """The Ockam BBS+ signature impementation.
"""

[features]

[dependencies]
bls12_381_plus = "0.5"
blake2 = { version = "0.9", default-features = false }
digest = { version = "0.9", default-features = false }
ff = "0.10"
group = "0.10"
hmac-drbg = "0.3"
managed = { version = "0.8", features = ["map"] }
pairing = "0.20"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
signature_core = { version = "0.17.0-dev"                          , path = "../signature_core" }
signature_bls = { version = "0.15.0-dev"                          , path = "../signature_bls" }
subtle = { version = "2.4", default-features = false }
typenum = "1.13"
zeroize = { version = "1.2", features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.3"
rand = "0.8.3"
