[package]
name = "tcp_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
ockam = {path = "../../ockam/ockam", version = "*"}
ockam_node = {path = "../../ockam/ockam_node", version = "*"}
ockam_router = {path = "../../ockam/ockam_router", version = "*"}
ockam_transport_tcp = {path = "../../ockam/ockam_transport_tcp", version = "*"}
serde_bare = "0.3.0"
serde = {version = "1.0.120", features = ["derive"]}
async-trait =  { version = "0.1.42" }
tokio = {version = "1.1.0", features = ["rt-multi-thread","sync","net","macros","time"]}
