[package]
name = "ockam_key_exchange_core"
version = "0.23.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","embedded", "no-std"]
keywords = ["ockam", "crypto", "kex", "cryptography", "encryption"]
description = """The Ockam Key Exchange trait.
"""

[features]
default = ["std"]

# Option (enabled by default): "std" enables functionality expected to be available on a standard platform.
std = ["ockam_core/std", "ockam_vault_core/std"]

# Feature: "no_std" enables functionality required for platforms without the standard library.
no_std = ["ockam_core/no_std", "ockam_vault_core/no_std"]

# Feature: "alloc" enables support for heap allocation on "no_std" platforms, requires nightly.
alloc = ["ockam_core/alloc", "ockam_vault_core/alloc"]

# Option: "unsafe_random" enables development support for random
# number generation on no_std platforms that do not yet have
# cryptographically secure implementations.
# WARNING: Under no circumstances should this ever be enabled in
#          production builds!
unsafe_random = ["ockam_core/unsafe_random"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.31.0"    , default_features = false }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.25.0"    , default_features = false }
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }
