[package]
name = "ockam_key_exchange_core"
version = "0.48.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/build-trust/ockam"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_core"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "embedded",
    "no-std",
]
keywords = ["ockam", "crypto", "kex", "cryptography", "encryption"]
description = """The Ockam Key Exchange trait.
"""
publish = true
rust-version = "1.56.0"

[features]
default = ["std"]

# Option (enabled by default): "std" enables functionality expected to be available on a standard platform.
std = ["ockam_core/std", "alloc"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library, requires nightly.
no_std = ["ockam_core/no_std"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["ockam_core/alloc"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.57.0", default_features = false }
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }
