[package]
name = "ockam_key_exchange_core"
version = "0.17.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","embedded", "no-std"]
keywords = ["ockam", "crypto", "kex", "cryptography", "encryption"]
description = """The Ockam Key Exchange trait.
"""

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.25.0-dev"                           }
ockam_vault_core = { path = "../ockam_vault_core" , version = "0.19.0-dev"                           }
zeroize = { version = "1.1", features = ["zeroize_derive"] }
