[package]
name = "ockam_vault_test_suite"
categories = ["cryptography", "asynchronous", "authentication","network-programming", "embedded"]
description = """Ockam Vault test suite.
"""
version = "0.29.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
keywords = ["ockam", "crypto", "cryptography", "network-programming", "encryption"]
readme = "README.md"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_test_suite"
publish = true

[dependencies]
ockam_core = {path = "../ockam_core", version = "^0.40.0"}
ockam_vault_core = {path = "../ockam_vault_core", version = "^0.34.0"}
arrayref = "0.3"
