[package]
name = "ockam_vault_test_suite"
categories = ["cryptography", "asynchronous", "authentication","network-programming", "embedded"]
description = """Ockam Vault test suite.
"""
version = "0.14.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
keywords = ["ockam", "crypto", "cryptography", "network-programming", "encryption"]
readme = "README.md"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_test_suite"

[dependencies]
ockam_core = {path = "../ockam_core", version = "0.25.0-dev"                          }
ockam_vault_core = {path = "../ockam_vault_core", version = "0.19.0-dev"                          }
