[package]
name = "ockam_vault_sync_core"
version = "0.16.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_sync_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "algorithms"]
keywords = ["ockam", "crypto", "cryptography"]
description = """Syncronous wrapper that allows to have multiple Vault instances,
that talk to the same Vault implementation without need for synchronization primitives
"""

[features]
default = []
software_vault = ["ockam_vault"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.25.0-dev"                           }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.19.0-dev"                           }
ockam_vault = { path = "../ockam_vault", version = "0.19.0-dev"                          , optional = true }
ockam_node = {path = "../ockam_node", version = "0.23.0-dev"                          }
zeroize = { version = "1.1", features = ["zeroize_derive"] }
serde = {version = "1.0", features = ["derive"]}
serde-big-array = "0.3"
tracing = "0.1"
async-trait = "0.1"
rand = "0.8"

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "0.19.0-dev"                           }
ockam_vault_test_suite = { path = "../ockam_vault_test_suite", version = "0.14.0-dev"                           }
ockam_vault_test_attribute = { path = "../ockam_vault_test_attribute", version = "0.16.0-dev"                          }
