[package]
name = "ockam_vault_sync_core"
version = "0.40.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_sync_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "algorithms"]
keywords = ["ockam", "crypto", "cryptography"]
description = """Syncronous wrapper that allows to have multiple Vault instances,
that talk to the same Vault implementation without need for synchronization primitives
"""
publish = true
rust-version = "1.56.0"

[features]
default = ["std"]
software_vault = ["ockam_vault"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = [
    "ockam_core/std",
    "ockam_macros/std",
    "ockam_vault/std",
    "ockam_node/std",
    "rand/std",
    "rand/std_rng",
    "alloc",
]

# Feature: "no_std" enables functionality required for platforms
# without the standard library, requires nightly.
no_std = [
    "ockam_core/no_std",
    "ockam_macros/no_std",
    "ockam_vault/no_std",
    "ockam_node/no_std",
    "rand_pcg",
]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = [
    "ockam_core/alloc",
    "ockam_vault/alloc",
    "ockam_node/alloc",
    "serde/alloc",
]

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.49.0", default_features = false }
ockam_macros = { path = "../ockam_macros", version = "^0.10.0", default_features = false }
ockam_vault = { path = "../ockam_vault", version = "^0.42.0", default_features = false, optional = true }
ockam_node = { path = "../ockam_node", version = "^0.48.0", default_features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-big-array = "0.3"
tracing = { version = "0.1", default_features = false }
rand = { version = "0.8", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false, optional = true }

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "^0.42.0"}
ockam_vault_test_suite = { path = "../ockam_vault_test_suite", version = "^0.37.0"}
tokio = { version = "1.8", default-features = false, features = ["sync"]}
