[package]
name = "ockam_vault_sync_core"
version = "0.17.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_sync_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "algorithms"]
keywords = ["ockam", "crypto", "cryptography"]
description = """Syncronous wrapper that allows to have multiple Vault instances,
that talk to the same Vault implementation without need for synchronization primitives
"""

[features]
default = ["std"]
software_vault = ["ockam_vault"]

# Option (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_core/std", "ockam_vault_core/std", "ockam_vault/std", "ockam_node/std", "rand/std", "rand/std_rng"]

# Option: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["ockam_core/no_std", "ockam_vault_core/no_std", "ockam_vault/no_std", "ockam_node/no_std", "rand_pcg"]

# Option: "alloc" enables support for heap allocation on "no_std"
# platforms, requires nightly.
alloc = ["ockam_core/alloc", "ockam_vault_core/alloc", "ockam_vault/alloc", "ockam_node/alloc", "serde/alloc"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.26.0" , default_features = false }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.20.0" , default_features = false }
ockam_vault = { path = "../ockam_vault", version = "0.20.0" , default_features = false, optional = true }
ockam_node = { path = "../ockam_node", version = "0.24.0" , default_features = false }
zeroize = { version = "1.1", features = ["zeroize_derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-big-array = "0.3"
tracing = { version = "0.1", default_features = false }
async-trait = "0.1"
rand = { version = "0.8", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false, optional = true }

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "0.20.0"                              }
ockam_vault_test_suite = { path = "../ockam_vault_test_suite", version = "0.15.0"                              }
ockam_vault_test_attribute = { path = "../ockam_vault_test_attribute", version = "0.17.0"                             }
