[package]
name = "ockam_node_test_attribute"
categories = ["cryptography", "asynchronous", "authentication","network-programming"]
authors = ["Ockam Developers"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node_test_attribute"
readme = "README.md"
keywords = ["ockam", "crypto", "macro", "proc-macro", "attribute"]
description = """
Ockam node attribute proc_macros.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[features]
default = ["std"]
std = []
no_std = []
alloc = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["full", "extra-traits"]}

[dev-dependencies]
ockam = { path = "../ockam",  default-features = false, features = ["std"] }
ockam_node = { path = "../ockam_node", default-features = false, features = ["std"] }
trybuild = "1.0"
