[package]
name = "ockam_entity"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_entity"
readme = "README.md"
categories = ["cryptography", "authentication"]
keywords = ["ockam", "crypto", "encryption", "authentication"]
description = """
"""

[features]
default = ["std", "software_vault", "noise_xx"]
noise_xx = ["ockam_key_exchange_xx"]
software_vault = ["ockam_vault", "ockam_vault_sync_core", "ockam_vault_sync_core/software_vault"]
std = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.12.0" }
ockam_node = {path = "../ockam_node", version = "0.10.0"}
ockam_vault_core = { path = "../ockam_vault_core", version = "0.6.0" }
ockam_vault_sync_core = {path = "../ockam_vault_sync_core", version = "0.3.0", optional = true}
ockam_vault = {path = "../ockam_vault", version = "0.6.0", optional = true}
ockam_channel = {path = "../ockam_channel", version = "0.7.0"}
ockam_key_exchange_xx = { path = "../ockam_key_exchange_xx", version = "0.4.0", optional = true}
async-trait = "0.1.42"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-big-array = "0.3"
serde_bare = "0.4"
rand = "0.8"
tracing = "0.1"

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "0" }
ockam_vault_sync_core = { path = "../ockam_vault_sync_core", version = "0" }
