[package]
name = "ockam_transport_udp"
version = "0.19.0"
authors = ["Ockam Developers"]
autoexamples = false
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "network-programming",
  "embedded",
]
edition = "2021"
homepage = "https://github.com/ockam-network/ockam"
keywords = ["ockam", "crypto", "network", "networking", "tcp"]
license = "Apache-2.0"
publish = false
readme = "README.md"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_transport_tcp"
rust-version = "1.56.0"
description = """
TCP Transport for the Ockam Routing Protocol.
"""

[features]
default = ["std"]
std = ["ockam_macros/std"]
alloc = []

[dependencies]
bytes = "1.4.0"
futures-util = "0.3"
hashbrown = { version = "0.13" }
ockam_core = { path = "../ockam_core", version = "^0.78.0", default_features = false }
ockam_node = { path = "../ockam_node", version = "^0.81.0" }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.51.0" }
rand = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
tokio = { version = "1.27.0", features = ["rt-multi-thread", "sync", "net", "macros", "time", "io-util"] }
tokio-util = { version = "0.7.7", features = ["net", "codec"] }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
ockam = { path = "../ockam", version = "^0.84.0" }
ockam_macros = { path = "../ockam_macros", version = "^0.28.0" }

[[example]]
name = "client"

[[example]]
name = "echo_server"

[[example]]
name = "rendezvous_server"
