[package]
name = "ockam_transport_tcp"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_transport_tcp"
readme = "README.md"
keywords = ["ockam", "tcp", "ockam-transport"]
categories = ["network-programming", "asynchronous"]
description = """
TCP Transport for the Ockam Routing Protocol.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]
autoexamples = false

[features]
default = ["std"]
std = []

[dependencies]
ockam_core = {path = "../ockam_core", version = "*"}
ockam_router = {path = "../ockam_router", version = "*"}
serde_bare = "0.3.0"
serde = {version = "1.0.120", features = ["derive"]}
tokio = {version = "1.1.0", features = ["rt-multi-thread","sync","net","macros","time"]}
async-trait = "0.1.42"
futures = " 0.3.10"
rand = "0.7"

[dev-dependencies]
trybuild = {version = "1.0.38", features = ["diff"]}
