[package]
name = "ockam_transport_tcp"
version = "0.116.0"
authors = ["Ockam Developers"]
autoexamples = false
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "network-programming",
  "embedded",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "network", "networking", "tcp"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_transport_tcp"
rust-version = "1.56.0"
description = """
TCP Transport for the Ockam Routing Protocol.
"""

[features]
default = ["std", "ring"]
std = ["ockam_macros/std", "ockam_transport_core/std", "opentelemetry"]
no_std = ["ockam_macros/no_std", "ockam_transport_core/no_std"]
alloc = []
aws-lc = ["tokio-rustls/aws-lc-rs"]
ring = ["tokio-rustls/ring"]

[dependencies]
cfg-if = "1.0.0"
ockam_core = { path = "../ockam_core", version = "^0.110.0" }
ockam_macros = { path = "../ockam_macros", version = "^0.34.0" }
ockam_node = { path = "../ockam_node", version = "^0.118.0" }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.83.0" }
opentelemetry = { version = "0.23.0", features = ["logs", "metrics", "trace"], optional = true }
rand = "0.8"
rustls-native-certs = "0.7"
serde = { version = "1.0", default-features = false, features = ["derive"] }
socket2 = { version = "0.5.6", features = ["all"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "sync", "net", "macros", "time", "io-util"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "tls12"] }
tracing = { version = "0.1", default-features = false }
