[package]
name = "ockam_transport_tcp"
version = "0.19.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_transport_tcp"
readme = "README.md"
keywords = ["ockam", "crypto", "network", "networking", "tcp"]
categories = ["cryptography", "asynchronous", "authentication","network-programming", "embedded"]
description = """
TCP Transport for the Ockam Routing Protocol.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]
autoexamples = false

[features]
default = ["std"]
std = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.25.0-dev"                           }
ockam_node = { path = "../ockam_node", version = "0.23.0-dev"                           }
serde_bare = "0.3.0"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1.8", features = ["rt-multi-thread","sync","net","macros","time"]}
futures = " 0.3.10"
async-trait = "0.1"
rand = "0.7"
hashbrown =  { version = "0.9"}
tracing = "0.1"

[dev-dependencies]
trybuild = {version = "1.0", features = ["diff"]}
