[package]
name = "ockam_transport_tcp"
version = "0.92.0"
authors = ["Ockam Developers"]
autoexamples = false
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "network-programming",
  "embedded",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "network", "networking", "tcp"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_transport_tcp"
rust-version = "1.56.0"
description = """
TCP Transport for the Ockam Routing Protocol.
"""

[features]
default = ["std"]
std = ["ockam_macros/std", "ockam_transport_core/std"]
no_std = ["ockam_macros/no_std", "ockam_transport_core/no_std"]
alloc = []

[dependencies]
cfg-if = "1.0.0"
hashbrown = { version = "0.14", default-features = false }
ockam_core = { path = "../ockam_core", version = "^0.89.0" }
ockam_macros = { path = "../ockam_macros", version = "^0.32.0" }
ockam_node = { path = "../ockam_node", version = "^0.94.0" }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.62.0" }
rand = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
socket2 = { version = "0.5.4", features = ["all"] }
tokio = { version = "1.33", features = ["rt-multi-thread", "sync", "net", "macros", "time", "io-util"] }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
