[package]
name = "ockam_transport_tcp"
version = "0.66.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/build-trust/ockam"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_transport_tcp"
readme = "README.md"
keywords = ["ockam", "crypto", "network", "networking", "tcp"]
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "network-programming",
    "embedded",
]
description = """
TCP Transport for the Ockam Routing Protocol.
"""
autoexamples = false
publish = true
rust-version = "1.56.0"

[features]
default = ["std"]
std = ["ockam_macros/std"]
alloc = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.65.0" }
ockam_node = { path = "../ockam_node", version = "^0.68.0" }
ockam_macros = { path = "../ockam_macros", version = "^0.19.0" }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.38.0" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tokio = { version = "1.8", features = [
    "rt-multi-thread",
    "sync",
    "net",
    "macros",
    "time",
    "io-util",
] }
rand = "0.7"
hashbrown = { version = "0.9", default-features = false }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
