[package]
name = "ockam_node_attribute"
categories = ["cryptography", "asynchronous", "authentication","network-programming"]
version = "0.14.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node_attribute"
readme = "README.md"
keywords = ["ockam", "crypto", "macro", "proc-macro", "attribute"]
description = """
Ockam node attribute proc_macro.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = {version = "1.0", features = ["full", "extra-traits"]}
