[package]
name = "ockam_node_attribute"
version = "0.1.4"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_node_attribute"
readme = "README.md"
keywords = ["ockam", "proc_macro"]
description = """
Ockam node attribute proc_macro.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.8"
syn = {version = "1.0.58", features = ["full", "extra-traits"]}
