[package]
name = "ockam_transport_uds"
version = "0.21.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "network-programming",
  "embedded",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "network", "networking", "uds"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_transport_uds"
rust-version = "1.64.0"
description = """
Unix Domain Socket (UDS) Transport for the Ockam Routing Protocol
"""

[features]
default = ["std"]
std = ["ockam_macros/std"]
alloc = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.89.0" }
ockam_macros = { path = "../ockam_macros", version = "^0.32.0" }
ockam_node = { path = "../ockam_node", version = "^0.94.0" }
ockam_transport_core = { path = "../ockam_transport_core", version = "^0.62.0" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
socket2 = "0.5.4"
tokio = { version = "1.33", features = ["rt-multi-thread", "sync", "net", "macros", "time", "io-util"] }
tracing = "0.1"
