[package]
name = "ockam_core"
version = "0.25.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","network-programming", "embedded"]
keywords = ["ockam", "crypto", "p2p", "cryptography", "encryption"]
description = """
Core types of the Ockam library.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[features]
default = ["std"]

# Requires the Rust Standard Library.
std = ["serde_bare", "serde", "async-trait", "hex/std"]

# Requires the Rust alloc library
alloc = []

# No alloc and no standard library
no_std = ["heapless"]

[dependencies]
async-trait =  { version = "0.1", optional = true }
serde_bare = { version =  "0.4", optional = true }
hashbrown =  { version = "0.11", features = ["serde"]}
heapless = { version = "0.7", optional = true }
hex = { version = "0.4", default-features = false }
serde =  { version = "1.0", features = ["derive"], optional = true }
rand = "0.8"
