[package]
name = "ockam_core"
version = "0.89.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "network-programming",
  "embedded",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "p2p", "cryptography", "encryption"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_core"
rust-version = "1.56.0"
description = """
Core types of the Ockam library.
"""

[features]
default = ["std", "error-traces"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = [
  "alloc",
  "hex/std",
  "minicbor/std",
  "rand/std",
  "rand/std_rng",
  "serde_bare/std",
  "ockam_macros/std",
  "once_cell/std",
  "tinyvec/std",
]

# Feature: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["core2", "hex", "rand_pcg", "spin", "ockam_macros/no_std"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = [
  "core2/alloc",
  "heapless",
  "hex/alloc",
  "minicbor/alloc",
  "serde/alloc",
  "serde_bare/alloc",
]

# Feature: "error-traces" cover whether not our errors capture
# backtraces and/or spantraces by default.
error-traces = [
  "tracing-error",
  "once_cell",
] # "backtrace" is disabled by default since it slows down the code drastically

# Feature: "debugger" enables functionality to trace addresses and
# message flows within Ockam apps.
debugger = []

[dependencies]
async-trait = "0.1.73"
backtrace = { version = "0.3", default-features = false, features = ["std", "serialize-serde"], optional = true }
cfg-if = "1.0"
core2 = { version = "0.4.0", default-features = false, optional = true }
futures-util = { version = "0.3.17", default-features = false, features = ["alloc", "async-await-macro", "sink"] }
hashbrown = { version = "0.14", default-features = false, features = ["ahash", "serde"] }
heapless = { version = "0.7.1", optional = true }
hex = { version = "0.4", default-features = false, optional = true }
minicbor = { version = "0.20.0", features = ["derive"] }
ockam_macros = { path = "../ockam_macros", version = "^0.32.0", default_features = false }
once_cell = { version = "1", optional = true, default-features = false }
rand = { version = "0.8", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_bare = { version = "0.5.0", default-features = false }
spin = { version = "0.9.8", default-features = false, features = ["mutex", "rwlock", "spin_mutex"], optional = true }
subtle = { version = "2", default-features = false }
tinyvec = { version = "1.6.0", features = ["rustc_1_57"] }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
tracing-error = { version = "0.2", default-features = false, optional = true }
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }

[dev-dependencies]
cddl-cat = { version = "0.6.1" }
quickcheck = "1.0.1"
serde_cbor = { version = "0.11.2" }
tokio = { version = "1.33.0", features = ["full"] }
