[package]
name = "signature_bls"
version = "0.15.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/signature_bls"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std","algorithms"]
keywords = ["ockam", "crypto", "signature", "signing", "bls"]
description = """The Ockam BLS signature impementation.
"""

[features]
default = ["alloc"]
alloc = ["bls12_381_plus/alloc"]

[dependencies]
bls12_381_plus = "0.5"
ff = "0.10"
group = "0.10"
hkdf = "0.11"
pairing = "0.20"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.9", default-features = false }
subtle = { version = "2.4", default-features = false }
vsss-rs = { version = "1.0.0", default-features = false }
zeroize = { version = "1.2", features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.3"
