[package]
name = "signature_bls"
version = "0.34.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/signature_bls"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "no-std",
    "algorithms",
]
keywords = ["ockam", "crypto", "signature", "signing", "bls"]
description = """The Ockam BLS signature impementation.
"""
publish = true
rust-version = "1.56.0"

[features]
default = ["alloc"]
alloc = []

[dependencies]
bls12_381_plus = { version = "0.5", default-features = false, features = [
    "alloc",
    "hashing",
    "pairings",
] }
ff = { version = "0.10", default-features = false }
group = "0.10"
hkdf = { version = "0.11", default-features = false }
pairing = "0.20"
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.9", default-features = false }
subtle = { version = "2.4", default-features = false }
vsss-rs = { version = "1.0.0", default-features = false }
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.3"
