[package]
name = "ockam_vault_core"
version = "0.26.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std","algorithms"]
keywords = ["ockam", "crypto", "cryptography", "authentication", "no-std"]
description = """The Ockam Vault trait.
"""

[features]
default = ["std"]
bls = []

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_core/std"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["ockam_core/no_std", "heapless"]

# Feature: "alloc" enables support for heap allocation on "no_std"
# platforms, requires nightly.
alloc = ["ockam_core/alloc", "serde/alloc"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.32.0"     , default_features = false }
heapless = { version = "0.7", features = ["serde"], optional = true }
serde = {version = "1.0", default-features = false, features = ["derive"]}
serde-big-array = "0.3"
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }
cfg-if = "1.0"
