[package]
name = "ockam_vault_core"
version = "0.4.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std","algorithms"]
keywords = ["ockam", "crypto", "cryptography", "authentication", "no-std"]
description = """The Ockam Vault trait.
"""

[features]
default = ["std"]
std = ["ockam_core/std"]
no_std = ["heapless"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.10.0" }
heapless = { version = "0.6", optional = true }
serde = {version = "1.0.125", features = ["derive"]}
serde-big-array = "0.3"
zeroize = { version = "1.1", features = ["zeroize_derive"] }
cfg-if = "1.0"
