[package]
name = "signature_core"
version = "0.36.0"
authors = ["Ockam Deveopers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/signatures_core"
readme = "README.md"
keywords = ["ockam", "crypto", "cryptography", "signatures", "signing"]
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "no-std",
    "algorithms",
]
description = """
Signature core types of the Ockam library.
"""
publish = true
rust-version = "1.56.0"

[dependencies]
blake2 = { version = "0.9", default-features = false }
bls12_381_plus = { version = "0.5", default-features = false, features = [
    "groups",
] }
digest = { version = "0.9", default-features = false }
ff = { version = "0.10", default-features = false }
group = "0.10"
hashbrown = { version = "0.11", default-features = false, features = ["ahash"] }
heapless = "0.7"
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"] }
subtle = { version = "2.4", default_features = false }
typenum = "1.13"
serde-big-array = "0.3"

[dev-dependencies]
rand = "0.8.3"
serde_json = "1.0"
