[package]
name = "signature_core"
version = "0.17.0-dev"
authors = ["Ockam Deveopers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/signatures_core"
readme = "README.md"
keywords = ["ockam", "crypto", "cryptography", "signatures", "signing"]
categories = ["cryptography", "asynchronous", "authentication","no-std", "algorithms"]
description = """
Signature core types of the Ockam library.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]


[dependencies]
blake2 = "0.9"
bls12_381_plus = "0.5"
digest = "0.9"
ff = "0.10"
group = "0.10"
hashbrown = { version = "0.11", features = ["serde"] }
heapless = "0.7"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
subtle = "2.4"
typenum = "1.13"
serde-big-array = "0.3"

[dev-dependencies]
rand = "0.8.3"
serde_json = "1.0"
