dev-version = true
push = true
disable-tag = true
tag = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="Unreleased\n### Added\n### Changed\n### Removed\n\n\n## v{{version}} - {{date}}"},
]