[package]
name = "ockam_key_exchange_xx"
version = "0.71.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/build-trust/ockam"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_xx"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "embedded",
    "no-std",
]
keywords = ["ockam", "crypto", "xx", "cryptography", "encryption"]
description = """The Ockam Noise XX implementation.
"""
publish = true
rust-version = "1.56.0"

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_core/std", "ockam_macros/std", "alloc"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library, requires nightly.
no_std = ["ockam_core/no_std", "ockam_macros/no_std"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["ockam_core/alloc", "ockam_macros/alloc"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.75.0", default_features = false }
ockam_macros = { path = "../ockam_macros", version = "^0.27.0", default_features = false }

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "^0.71.0" }
ockam_node = { path = "../ockam_node", version = "^0.78.0" }
hex = "0.4"
