[package]
name = "ockam_key_exchange_xx"
version = "0.78.0"
authors = ["Ockam Developers"]
categories = [
  "cryptography",
  "asynchronous",
  "authentication",
  "embedded",
  "no-std",
]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "xx", "cryptography", "encryption"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_xx"
rust-version = "1.56.0"
description = """The Ockam Noise XX implementation.
"""

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_vault/std"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library, requires nightly.
no_std = ["ockam_vault/no_std"]

# Feature: "alloc" enables support for heap allocation (implied by `feature = "std"`)
alloc = ["ockam_vault/alloc"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.81.0", default_features = false }
ockam_macros = { path = "../ockam_macros", version = "^0.30.0", default_features = false }
ockam_vault = { path = "../ockam_vault", default_features = false, version = "^0.77.0" }

[dev-dependencies]
hex = "0.4"
ockam_node = { path = "../ockam_node", version = "^0.84.0" }
