[package]
name = "ockam_key_exchange_xx"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_xx"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","peer-to-peer", "no-std"]
keywords = ["ockam", "crypto", "p2p", "xx"]
description = """The Ockam Noise XX impementation.
"""

[dependencies]
ockam_core = { version = "0.6.0", path = "../ockam_core" }
ockam_vault_core = { version = "0.3.0", path = "../ockam_vault_core" }
ockam_key_exchange_core = { version = "0.1.0", path = "../ockam_key_exchange_core" }
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
ockam_vault = { version = "0.3.0", path = "../ockam_vault" }
