version: "3.8"
networks:
  application_team:
    driver: bridge
services:
  # Start a consumer and producer node with ockam.
  #
  # Read kafka_ockam.dockerfile and run_ockam.sh to understand
  # how the node is set up.
  consumer:
    container_name: application_team-consumer
    build:
      context: .
      dockerfile: ../kafka_ockam.dockerfile
      args:
        OCKAM_VERSION: ${OCKAM_VERSION:-latest}
    environment:
      ENROLLMENT_TICKET: ${CONSUMER_ENROLLMENT_TICKET:-}
      OCKAM_DEVELOPER: ${OCKAM_DEVELOPER:-false}
    command:
      - -c
      - (
          sleep 10;
          echo "";
          echo "Messages sent from producers will appear shortly.";
          echo "It may take a couple of minutes for the first message to appear.";
          echo "=======================================================================";
          echo "Press Ctrl+C to stop the container at any time, then execute "\
          "'./run.sh cleanup' to remove all containers.";
          echo "";
          kafka-console-consumer.sh --topic demo --timeout-ms 50000 --bootstrap-server 127.0.0.1:9092 --max-messages 8 | tee output.txt;
          if [[ ! -s output.txt ]]; then
            echo "Failed to receive messages";
            exit 1;
          fi;
          echo "The example run was successful ü•≥.";
          echo "Messages received successfully, please Ctrl+C to exit";
          tail -f /dev/null;
        )
    networks:
      - application_team

  producer:
    container_name: application_team-producer
    build:
      context: .
      dockerfile: ../kafka_ockam.dockerfile
    environment:
      ENROLLMENT_TICKET: ${PRODUCER_ENROLLMENT_TICKET:-}
      OCKAM_DEVELOPER: ${OCKAM_DEVELOPER:-false}
    networks:
      - application_team
    command:
      - -c
      - (
          set -e;
          MESSAGES=(
            "Message - üî•"
            "Message - üåü"
            "Message - üöÄ"
            "Message - üê∑"
            "Message - ü¶Å"
            "Message - ü¶ä"
            "Message - üê∞"
            "Message - üêÆ"
          );
          sleep 10;
          for n in {0..7}; do
            sleep 2;
            echo -n $${MESSAGES[n]} | kafka-console-producer.sh
              --topic demo
              --bootstrap-server 127.0.0.1:9092
              --producer-property request.timeout.ms=30000;
          done;
          tail -f /dev/null
        )
