[package]
name = "ockam_channel"
version = "0.20.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std", "algorithms"]
keywords = ["ockam", "crypto", "encryption", "authentication"]
description = """Channel is an abstraction responsible for sending messages (usually over the network)
in encrypted and authenticated way.
"""

[features]
default = ["std"]
software_vault = ["ockam_vault", "ockam_vault_sync_core", "ockam_vault_sync_core/software_vault"]
noise_xx = ["ockam_key_exchange_xx"]
std = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.25.0-dev"                          }
ockam_key_exchange_core = { path = "../ockam_key_exchange_core", version = "0.17.0-dev"                          }
ockam_key_exchange_xx = { path = "../ockam_key_exchange_xx", version = "0.17.0-dev"                         , optional = true }
ockam_node = { path = "../ockam_node", version = "0.23.0-dev"                          }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.19.0-dev"                          }
ockam_vault_sync_core = { path = "../ockam_vault_sync_core", version = "0.16.0-dev"                         , optional = true }
ockam_vault = {path = "../ockam_vault", version = "0.19.0-dev"                         , optional = true}
serde_bare = "0.3.0"
rand = "0.8"
async-trait = "0.1"
serde = {version = "1.0", features = ["derive"]}
tracing = "0.1"

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "0.19.0-dev"                       }
ockam_key_exchange_xx = { path = "../ockam_key_exchange_xx", version = "0.17.0-dev"                       }
ockam_key_exchange_x3dh = { path = "../ockam_key_exchange_x3dh", version = "0.16.0-dev"                       }
ockam_vault_sync_core = { path = "../ockam_vault_sync_core", version = "0.16.0-dev"                       }
trybuild = {version = "1.0", features = ["diff"]}
