[package]
name = "ockam_channel"
version = "0.3.1"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std", "algorithms"]
keywords = ["ockam", "crypto", "encryption", "authentication"]
description = """Channel is an abstraction responsible for sending messages (usually over the network)
in encrypted and authenticated way.
"""

[features]
default = ["std"]
std = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.11.0" }
ockam_key_exchange_xx = { path = "../ockam_key_exchange_xx", version = "0.2.0" }
ockam_key_exchange_core = { path = "../ockam_key_exchange_core", version = "0.2.0" }
ockam_node = { path = "../ockam_node", version = "0.9.0" }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.4.1" }
ockam_vault_sync_core = { path = "../ockam_vault_sync_core", version = "0.1.0" }
ockam_vault = { path = "../ockam_vault", version = "0.4.1" }
serde_bare = "0.3.0"
rand = "0.8"
async-trait = "0.1.42"
serde = {version = "1.0.120", features = ["derive"]}
tracing = "0.1"

[dev-dependencies]
trybuild = {version = "1.0.38", features = ["diff"]}

