[package]
name = "tcp_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2021"
publish = false

[workspace]

[dependencies]
ockam = { path = "../../../ockam" }
ockam_node = { path = "../../../ockam_node" }
ockam_transport_tcp = { path = "../../../ockam_transport_tcp" }

# TODO: this dependency here is required because rustc doesn't yet
# support re-exporting attributes from crates.  Tracking issue:
# https://github.com/rust-lang/rust/issues/27812
serde = { version = "1.0", features = ["derive"] }
tracing = { version = "0.1", default-features = false }
