[package]
name = "ockam_transport_core"
version = "0.62.0"
authors = ["Ockam Developers"]
categories = ["network-programming", "asynchronous"]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "ockam-transport"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/implementations/rust/ockam/ockam_transport_core"
rust-version = "1.56.0"
description = """
Generic Transport primitives.
"""

[features]
default = ["std"]

# Feature (enabled by default): "std" enables functionality expected to
# be available on a standard platform.
std = ["ockam_core/std"]

# Feature: "no_std" enables functionality required for platforms
# without the standard library.
no_std = ["ockam_core/no_std"]

# Feature: "alloc" enables support for heap allocation on "no_std"
# platforms, requires nightly.
alloc = ["ockam_core/alloc"]

[dependencies]
ockam_core = { path = "../ockam_core", version = "^0.89.0", default_features = false }
tracing = { version = "0.1", default-features = false }
