[package]
name = "ockam_transport_core"
version = "0.2.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_transport_core"
readme = "README.md"
keywords = ["ockam", "ockam-transport"]
categories = ["network-programming", "asynchronous"]
description = """
Generic Transport primitives.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.28.0"    }
tracing = "0.1"
