[package]
name = "channel_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2021"
autobins = false
publish = false

[workspace]

[dependencies]
ockam = { path = "../../../ockam" }
ockam_node = { path = "../../../ockam_node" }
ockam_vault_sync_core = { path = "../../../ockam_vault_sync_core" }
ockam_vault = { path = "../../../ockam_vault" }
tracing = { version = "0.1", default-features = false }
ockam_transport_tcp = { path = "../../../ockam_transport_tcp" }
tokio = {version = "1.1.0", features = ["rt-multi-thread","sync","net","macros","time"]}
rand = "0.8.3"

[[bin]]
path = "src/bin/client.rs"
name = "channel_examples_client"

[[bin]]
path = "src/bin/server.rs"
name = "channel_examples_server"
