[package]
name = "signature_ps"
version = "0.33.0"
authors = ["Ockam Developers"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/signature_ps"
readme = "README.md"
categories = [
    "cryptography",
    "asynchronous",
    "authentication",
    "no-std",
    "algorithms",
]
keywords = ["ockam", "crypto", "signature", "signing", "bls"]
description = """The Ockam PS signature impementation.
"""
publish = true
rust-version = "1.56.0"

[features]

[dependencies]
blake2 = { version = "0.9", default-features = false }
signature_bls = { version = "^0.34.0", path = "../signature_bls" }
bls12_381_plus = { version = "0.5", default-features = false }
digest = { version = "0.9", default-features = false }
ff = { version = "0.10", default-features = false }
group = "0.10"
hmac-drbg = "0.3"
hkdf = { version = "0.11", default-features = false }
pairing = "0.20"
rand_core = "0.6"
rand_chacha = { version = "0.3", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
signature_core = { version = "^0.35.0", path = "../signature_core" }
subtle = { version = "2.4", default-features = false }
typenum = "1.13"
zeroize = { version = "1.4.2", features = ["zeroize_derive"] }

[dev-dependencies]
rand_xorshift = "0.3"
rand = "0.8"
