[package]
name = "example_test_helper"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false
rust-version = "1.56.0"

[dependencies]
cfg-if = "1.0.0"
duct = "0.13"
libc = "0.2"
regex = "1.8"
shellwords = "1.1"
tempfile = "3"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
