[package]
name        = "ockam_multiaddr"
version     = "0.16.0"
authors     = ["Ockam Developers"]
license     = "Apache-2.0"
edition     = "2021"
homepage    = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_multiaddr"
repository  = "https://github.com/ockam-network/ockam"
description = "An implementation of multiformats.io/multiaddr"
publish = true

[features]
std  = ["ockam_core/std", "unsigned-varint/std", "serde?/std"]
cbor = ["minicbor"]

[dependencies]
minicbor        = { version = "0.19.0", default-features = false, features = ["alloc"], optional = true }
once_cell       = { version = "1.17.1", default-features = false, features = ["alloc"] }
serde           = { version = "1.0.152", default-features = false, optional = true }
tinyvec         = { version = "1.5.1", features = ["alloc"] }
unsigned-varint = "0.7.1"

[dependencies.ockam_core]
version          = "0.76.0"
path             = "../ockam_core"
default-features = false
features         = ["no_std", "alloc"]

[dev-dependencies]
bincode         = "1.1.3"
multiaddr       = "0.17"
ockam_multiaddr = { path = ".", features = ["cbor", "std", "serde"] }
quickcheck      = "1.0.3"
rand            = "0.8.5"
serde_json      = "1.0.93"

