[package]
name = "ockam_multiaddr"
version = "0.32.0"
authors = ["Ockam Developers"]
edition = "2021"
homepage = "https://github.com/ockam-network/ockam/implementations/rust/ockam/ockam_multiaddr"
license = "Apache-2.0"
publish = true
repository = "https://github.com/ockam-network/ockam"
description = "An implementation of multiformats.io/multiaddr"

[features]
default = ["std"]
std = ["ockam_core/std", "unsigned-varint/std", "serde?/std"]
cbor = ["minicbor"]

[dependencies]
minicbor = { version = "0.20.0", default-features = false, features = ["alloc"], optional = true }
once_cell = { version = "1.18.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.188", default-features = false, optional = true }
tinyvec = { version = "1.5.1", features = ["alloc"] }
unsigned-varint = "0.7.2"

[dependencies.ockam_core]
version = "0.89.0"
path = "../ockam_core"
default-features = false
features = ["no_std", "alloc"]

[dev-dependencies]
bincode = "1.1.3"
multiaddr = "0.18"
ockam_multiaddr = { path = ".", features = ["cbor", "std", "serde"] }
quickcheck = "1.0.3"
rand = "0.8.5"
serde_json = "1.0.107"
