[package]
name = "ockam_vault_test_attribute"
version = "0.16.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_test_attribute"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","no-std", "algorithms"]
keywords = ["ockam", "crypto", "encryption", "authentication"]
description = """Ockam Vault test support attribute.
"""

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = {version = "1.0", features = ["full", "extra-traits"]}
