version: "3"
services:
  sat:
    image: suborbital/sat:2021.12.12-50
    command: sat /runnables/helloworld-rs/helloworld-rs.wasm
    environment:
      SAT_LOG_LEVEL: info
      SAT_PEERS: ws://ockam-inlet:${PORT:-4001}/meta/message
      SAT_RUNNABLE_IDENT: com.suborbital.ockam
      SAT_RUNNABLE_VERSION: v0.0.1
    networks:
      - suborbital-ockam
    volumes:
      - "./:/runnables/"
    depends_on:
      - ockam-inlet

  ockam-inlet:
    image: ghcr.io/build-trust/examples/tcp_inlet_and_outlet
    command: "04-inlet 0.0.0.0:${PORT:-4001} ${FORWARDING_ADDRESS}"
    ports:
      - "${PORT:-4001}:${PORT:-4001}"
    networks:
      - suborbital-ockam

networks:
  suborbital-ockam:
