name: cargo_update_check
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  cargo_update_check:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e382c8800a89ce43acb675131d9f30e74093d195a95047f87e9206a0c52c17a7
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Update and Check Ockam Example
        working-directory: examples/rust/get_started
        env:
          RUSTFLAGS: -Dwarnings
        run: |
          rm -rf Cargo.lock
          cargo update
          cargo check
