name: docker_builder
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'tools/docker/builder/**'

jobs:
  docker_builder:
    if: github.event.ref == 'refs/heads/develop' && github.repository_owner == 'ockam-network'
    runs-on: ubuntu-20.04
    environment:
      name: artifacts
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@a3b37769d28120b0a633f6985f454bbc6293c946
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ockam-network/artifacts
          event-type: docker_builder
          client-payload: '{"sha": "${{ github.sha }}"}'
