name: documentation_examples_check
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 */2 * * *'
  pull_request:

jobs:
    guide_examples_check:
        runs-on: ubuntu-20.04
        container:
            image: ghcr.io/ockam-network/ockam/builder@sha256:e382c8800a89ce43acb675131d9f30e74093d195a95047f87e9206a0c52c17a7
        steps:
          - name: Checkout
            uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

          - id: rust_build_ockam_ockam
            run: export OCKAM_HOME=$PWD && tools/docs/check_documentation.sh && tools/docs/run_examples.sh && tools/docs/run_kafka_example.sh && tools/docs/run_e2ee_example.sh
