name: elixir_clean_ockam_ockam_kafka
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'implementations/elixir/ockam/ockam/**'
      - 'build.gradle'
      - 'implementations/elixir/build.gradle'
      - 'settings.gradle'
      - 'implementations/elixir/settings.gradle'
      - 'implementations/elixir/ockam/ockam_kafka/**'

jobs:
  elixir_clean_ockam_ockam_kafka:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:3d41b8e711888f2525b786f7751016eca0770f65c3f925909e2c1db45c8c0714
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-gradle-cache-

      - id: elixir_clean_ockam_ockam_kafka
        working-directory: implementations/elixir
        run: ../../gradlew clean_ockam_ockam_kafka
