name: Gradle

on:
  workflow_dispatch:
  push:

  pull_request:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
  schedule:
    - cron:  '0 1 * * *'

jobs:
  list_gradle_tasks:
    name: List Gradle Tasks
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15] # windows-2016, windows-2019
        java: [8, 9, 10]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Java
        # https://github.com/actions/setup-java/releases/tag/v2.0.0
        uses: actions/setup-java@3bc31aaf88e8fc94dc1e632d48af61be5ca8721c # v2.3.0
        with:
          distribution: 'adopt'
          check-latest: true
          java-version: ${{ matrix.java }}

      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v2.3.4
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-cache-

      - name: List Tasks
        run: ./gradlew tasks --all
