name: Make

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
    branches:
      - develop
  schedule:
    # At 1 am.
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: nix develop ./tools/nix --ignore-environment --keep CI --command bash {0}

env:
  CI: true

jobs:
  full_build_in_release_mode:
    name: Make - full_build_in_release_mode
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/nix_installer
      - uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4
      - uses: ./.github/actions/elixir_cache
      - run: make
