name: Ockam Healthcheck Container Release

on:
  push:
    paths:
      - '.github/actions/ockam-healthcheck.yml'
      - 'implementations/elixir/ockam/ockam_healthcheck/**'
      - 'tools/docker/healthcheck/Dockerfile'
    branches:
      - develop

permissions:
  contents: read
  packages: write

env:
  ARTIFACT_NAME: ockam-healthcheck
  ORGANIZATION: ${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_ockam_healthcheck:
    name: "Build And Publish Ockam Healthcheck Container"
    runs-on: ubuntu-20.04
    environment: release

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          path: ockam-healthcheck

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: $ORGANIZATION
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        # TODO: change after new buildkit version gets fixed
        # https://github.com/moby/buildkit/issues/3347
        # https://github.com/docker/build-push-action/issues/761
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Build And Publish
        run: |
          docker buildx build --push \
            --tag ghcr.io/${ORGANIZATION}/${ARTIFACT_NAME}:latest \
            --file ./ockam-healthcheck/tools/docker/healthcheck/Dockerfile \
            --platform linux/amd64 .
