name: Crates IO Publish

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git Tag To Release From. Last Git Tag Is Used If Omitted
        required: false
      ockam_publish_exclude_crates:
        description: Exclude Specific Crates From Being Published
        required: false
      release_branch:
        description: Release Branch Where Recent Bump Occurred
        required: true
      ockam_publish_recent_failure:
        description: Indicate A Recent Failure
        type: choice
        default: 'false'
        options:
        - false
        - true

permissions:
  # Contents permission allows us read this repository.
  contents: read

defaults:
  run:
    shell: nix develop ./tools/nix#tooling --command bash {0}

jobs:
  publish_crates:
    runs-on: ubuntu-22.04
    environment: release
    name: "Publish Crates To Crates IO"
    steps:
      - name: Checkout Ockam
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0

      - uses: ./.github/actions/nix_installer

      - name: Publish Ockam Crates
        env:
          GIT_TAG: '${{ github.event.inputs.git_tag }}'
          OCKAM_PUBLISH_TOKEN: '${{ secrets.CRATES_IO_PUBLISH_TOKEN }}'
          OCKAM_PUBLISH_RECENT_FAILURE: '${{ github.event.inputs.ockam_publish_recent_failure }}'
          OCKAM_PUBLISH_EXCLUDE_CRATES: '${{ github.event.inputs.ockam_publish_exclude_crates }}'
        run: |
          bash -ex ./tools/scripts/release/crate-publish.sh
