name: rust_build_ockam_ockam_key_exchange_xx
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'implementations/rust/ockam/ockam_core/**'
      - 'implementations/rust/ockam/ockam_vault_core/**'
      - 'implementations/rust/ockam/ockam_key_exchange_core/**'
      - 'implementations/rust/ockam/ockam_vault_sync_core/**'
      - 'implementations/rust/ockam/ockam_vault/**'
      - 'implementations/rust/ockam/ockam_node/**'
      - 'build.gradle'
      - 'implementations/rust/build.gradle'
      - 'settings.gradle'
      - 'implementations/rust/settings.gradle'
      - 'implementations/rust/ockam/ockam_key_exchange_xx/**'

jobs:
  rust_build_ockam_ockam_key_exchange_xx:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:a4ee49a588dffbaef61eba29b4de0fe0be134b84aac3ab2f634ad92c74fe3802
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
            /root/.cargo/bin/
            /root/.cargo/registry/index/
            /root/.cargo/registry/cache/
            /root/.cargo/git/db/
            implementations/rust/ockam/ockam_key_exchange_xx/target
          key: ${{ runner.os }}-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-cache-

      - id: rust_build_ockam_ockam_key_exchange_xx
        working-directory: implementations/rust
        run: ../../gradlew build_ockam_ockam_key_exchange_xx
