name: rust_test_ockam_signature_bls
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'build.gradle'
      - 'implementations/rust/build.gradle'
      - 'settings.gradle'
      - 'implementations/rust/settings.gradle'
      - 'implementations/rust/ockam/signature_bls/**'

jobs:
  rust_test_ockam_signature_bls:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:3d41b8e711888f2525b786f7751016eca0770f65c3f925909e2c1db45c8c0714
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-gradle-cache-

      - id: rust_test_ockam_signature_bls
        working-directory: implementations/rust
        run: ../../gradlew test_ockam_signature_bls
