name: rust_test_ockam_signature_bbs_plus
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'implementations/rust/ockam/signature_core/**'
      - 'implementations/rust/ockam/signature_bls/**'
      - 'build.gradle'
      - 'implementations/rust/build.gradle'
      - 'settings.gradle'
      - 'implementations/rust/settings.gradle'
      - 'implementations/rust/ockam/signature_bbs_plus/**'

jobs:
  rust_test_ockam_signature_bbs_plus:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:cbda96698696625b29da843da8c7d1b37b775d5767d14bbf0f8233174735dca8
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: rust_test_ockam_signature_bbs_plus
        working-directory: implementations/rust
        run: ../../gradlew test_ockam_signature_bbs_plus
