name: rust_lint_ockam_ockam_vault_sync_core
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'implementations/rust/ockam/ockam_core/**'
      - 'implementations/rust/ockam/ockam_vault_core/**'
      - 'implementations/rust/ockam/ockam_vault/**'
      - 'implementations/rust/ockam/ockam_node/**'
      - 'implementations/rust/ockam/ockam_vault_test_suite/**'
      - 'implementations/rust/ockam/ockam_vault_test_attribute/**'
      - 'build.gradle'
      - 'implementations/rust/build.gradle'
      - 'settings.gradle'
      - 'implementations/rust/settings.gradle'
      - 'implementations/rust/ockam/ockam_vault_sync_core/**'

jobs:
  rust_lint_ockam_ockam_vault_sync_core:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:3d41b8e711888f2525b786f7751016eca0770f65c3f925909e2c1db45c8c0714
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: rust_lint_ockam_ockam_vault_sync_core
        working-directory: implementations/rust
        run: ../../gradlew lint_ockam_ockam_vault_sync_core
