name: rust_lint_ockam_ockam_vault_test_suite
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'implementations/rust/ockam/ockam_core/**'
      - 'implementations/rust/ockam/ockam_vault_core/**'
      - 'build.gradle'
      - 'implementations/rust/build.gradle'
      - 'settings.gradle'
      - 'implementations/rust/settings.gradle'
      - 'implementations/rust/ockam/ockam_vault_test_suite/**'


jobs:
  rust_lint_ockam_ockam_vault_test_suite:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e382c8800a89ce43acb675131d9f30e74093d195a95047f87e9206a0c52c17a7
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: rust_lint_ockam_ockam_vault_test_suite
        working-directory: implementations/rust
        run: ../../gradlew lint_ockam_ockam_vault_test_suite
