name: OSSF Scorecards

permissions:
  contents: read

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: '0 1 * * 1'
  push:
    branches: [ develop ]

jobs:
  analyze:
    name: Scorecards - Analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write # Needed to upload results to code-scanning dashboard.
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          persist-credentials: false

      - name: Analyze
        uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@4238421316c33d73aeea2801274dd286f157c2bb
        with:
          sarif_file: results.sarif
