name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Check spelling
        uses: crate-ci/typos@4550e7d4371fcf55649adfcda9b77716658504b1
        with:
          config: tools/typos/typos.toml
