name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Check spelling
        uses: crate-ci/typos@c97d621b6b01d8b0258538ca15abeca5c5764601
        with:
          config: tools/typos/typos.toml
